#!/usr/bin/env bash
SCRIPT="${0##*/}"

## Source invocation ?
if [ "${BASH_LINENO[0]}" -ne 0 ]; then
  # Environment variables
  echo "INFO[${SCRIPT}]: Unsetting environment variables ..."
  unset EXOSCALE_ZONE
else
  set -e
  SCRIPT_DIR="$(dirname "$(realpath -e "${0}")")"

  # Files/directories
  echo "INFO[${SCRIPT}]: Removing files/directories ..."
  cd "${SCRIPT_DIR}"
  rm -rfv \
     ./terraform/output \
     ./terraform/*.tfstate* \
     ./terraform/.terraform*
fi
