---
name: Sync Tailscale ACLs

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: deploy-acl
        name: Deploy ACL
        if: github.event_name == 'push'
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.TS_API_KEY }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply

      - id: test-acl
        name: Test ACL
        if: github.event_name == 'pull_request'
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.TS_API_KEY }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: test
